<?php

/**
 * @file
 * Contains dataform.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dataform_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dataform module.
    case 'help.page.dataform':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DataForm Entity Type and DataForm related fields') . '</p>';
      return $output;

    default:
  }
}
