<?php

/**
 * @file
 * Contains collection_field_relation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function collection_field_relation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the collection_field_relation module.
    case 'help.page.collection_field_relation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Used for saving the collection field relation details') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function collection_field_relation_theme() {
  return [
    'collection_field_relation' => [
      'render element' => 'children',
    ],
  ];
}
