<?php

/**
 * @file
 * Contains collection_relations.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function collection_relations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the collection_relations module.
    case 'help.page.collection_relations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Used for saving the relational field details') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function collection_relations_theme() {
  return [
    'collection_relations' => [
      'render element' => 'children',
    ],
  ];
}
