<?php

/**
 * @file
 * Contains opsyd_subgroups.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function opsyd_subgroups_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opsyd_subgroups module.
    case 'help.page.opsyd_subgroups':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opsyd_subgroups_theme() {
  return [
    'opsyd_subgroups' => [
      'render element' => 'children',
    ],
  ];
}
